---
apiVersion: v1
kind: Namespace
metadata:
  name: whois

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whois
  namespace: whois
  labels:
    name: whois
spec:
  replicas: 3
  selector:
    matchLabels:
      name: whois
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/trace-collector: oc-collector.tracing:55678
      labels:
        name: whois
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: msfidelis/whois:v1
        name: whois
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: "256m"
            memory: "512m"

---
kind: Service
apiVersion: v1
metadata:
  name: whois
  namespace: whois
spec:
  selector:
    name: whois
  ports:
    - protocol: TCP
      port: 8080
      name: web
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whois
  namespace: whois
spec:
  rules:
  - http:
      paths:
      - path: /whois
        backend:
          serviceName: whois
          servicePort: 8080

  tls:
  - hosts:
    - k8s.raj.ninja
    secretName: whois
---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: whois
  namespace: whois
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: whois
  service:
    port: 8080
  analysis:
    interval: 10s
    threshold: 5
    stepWeight: 10
    maxWeight: 100
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      thresholdRange:
        max: 500
      interval: 1m